### ISSUE TITLE
Building Python packages fails with "No module named pip"

### ISSUE THREAD

**Issue by jtilly** [conda/rattler#1018]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

As of a couple of hours ago, I can't build basic python packages with rattler-build.

Example:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: test123
  version: 1

build:
  number: 0
  script: $PYTHON -m pip --help  # instead of pip install to keep the reproducer small
  noarch: python
requirements:
  host:
    - python
    - pip
 ```

produces

```
/private/tmp/conda.recipe rattler-build build

 ╭─ Finding outputs from recipe
 │ Found 1 variants
 │ Build variant: test123-1-pyh4616a5c_0
 │ 
 │ ╭─────────────────┬─────────╮
 │ │ Variant         ┆ Version │
 │ ╞═════════════════╪═════════╡
 │ │ target_platform ┆ noarch  │
 │ ╰─────────────────┴─────────╯
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Running build for recipe: test123-1-pyh4616a5c_0
 │
 │ ╭─ Fetching source code
 │ │ No sources to fetch
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 │ ╭─ Resolving environments
 │ │ 
 │ │ Resolving host environment:
 │ │   Platform: osx-arm64 [__unix=0=0, __osx=14.6.1=0, __archspec=1=m1]
 │ │   Channels: 
 │ │    - file:///private/tmp/conda.recipe/output/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - python 3.13.1.*
 │ │ 
 │ │ ╭─────────────────┬────────────┬────────────────────┬─────────────┬────────────
 │ │ ╮
 │ │ │ Package         ┆ Version    ┆ Build              ┆ Channel     ┆ Size       
 │ │ │
 │ │ ╞═════════════════╪════════════╪════════════════════╪═════════════╪════════════
 │ │ ╡
 │ │ │ bzip2           ┆ 1.0.8      ┆ h99b78c6_7         ┆ conda-forge ┆ 120.03 KiB 
 │ │ │
 │ │ │ ca-certificates ┆ 2024.12.14 ┆ hf0a4a13_0         ┆ conda-forge ┆ 153.41 KiB 
 │ │ │
 │ │ │ libexpat        ┆ 2.6.4      ┆ h286801f_0         ┆ conda-forge ┆ 63.18 KiB  
 │ │ │
 │ │ │ libffi          ┆ 3.4.2      ┆ h3422bc3_5         ┆ conda-forge ┆ 38.11 KiB  
 │ │ │
 │ │ │ liblzma         ┆ 5.6.3      ┆ h39f12f2_1         ┆ conda-forge ┆ 96.81 KiB  
 │ │ │
 │ │ │ libmpdec        ┆ 4.0.0      ┆ h99b78c6_0         ┆ conda-forge ┆ 67.64 KiB  
 │ │ │
 │ │ │ libsqlite       ┆ 3.47.2     ┆ h3f77e49_0         ┆ conda-forge ┆ 830.62 KiB 
 │ │ │
 │ │ │ libzlib         ┆ 1.3.1      ┆ h8359307_2         ┆ conda-forge ┆ 45.35 KiB  
 │ │ │
 │ │ │ ncurses         ┆ 6.5        ┆ h7bae524_1         ┆ conda-forge ┆ 783.52 KiB 
 │ │ │
 │ │ │ openssl         ┆ 3.4.0      ┆ h81ee809_1         ┆ conda-forge ┆ 2.80 MiB   
 │ │ │
 │ │ │ pip             ┆ 24.3.1     ┆ pyh145f28c_2       ┆ conda-forge ┆ 1.18 MiB   
 │ │ │
 │ │ │ python          ┆ 3.13.1     ┆ h4f43103_103_cp313 ┆ conda-forge ┆ 11.18 MiB  
 │ │ │
 │ │ │ python_abi      ┆ 3.13       ┆ 5_cp313            ┆ conda-forge ┆ 6.17 KiB   
 │ │ │
 │ │ │ readline        ┆ 8.2        ┆ h92ec313_1         ┆ conda-forge ┆ 244.48 KiB 
 │ │ │
 │ │ │ tk              ┆ 8.6.13     ┆ h5083fa2_1         ┆ conda-forge ┆ 3.00 MiB   
 │ │ │
 │ │ │ tzdata          ┆ 2024b      ┆ hc8b5060_0         ┆ conda-forge ┆ 119.49 KiB 
 │ │ │
 │ │ ╰─────────────────┴────────────┴────────────────────┴─────────────┴────────────
 │ │ ╯
 │ │ 
 │ │ Finalized run dependencies:
 │ │ ╭──────────────────┬────────────────────────╮
 │ │ │ Name             ┆ Spec                   │
 │ │ ╞══════════════════╪════════════════════════╡
 │ │ │ Run dependencies ┆                        │
 │ │ │ python           ┆ (RE of [host: python]) │
 │ │ ╰──────────────────┴────────────────────────╯
 │ │
 │ ╰─────────────────── (took 1 second)
 │ 
 │ Installing build environment
 │ ✔ Successfully updated the build environment
 │ 
 │ Installing host environment
 │ ✔ Successfully updated the host environment
 │
 │ ╭─ Running build script
 │ │ + $PREFIX/bin/python -m pip --help
 │ │ $PREFIX/bin/python: No module named pip
 │ │ × error Script failed with status 1
 │ │ × error Work directory: '/private/tmp/conda.recipe/output/bld/rattler-build_test
 │ │ × error 123_1736288639/work'
 │ │ × error To debug the build, run it manually in the work directory (execute the `
 │ │ × error ./conda_build.sh` or `conda_build.bat` script)
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 ╰─────────────────── (took 2 seconds)
Error: 
  × Script failed
```

This works fine when I pin `python <3.13.1`.

Is it possible that https://github.com/conda-forge/python-feedstock/pull/764 broke rattler-build?

`conda-build` stills works, e.g.

```
package:
  name: test123
  version: 1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip --help"

requirements:
  host:
    - python =3.13.1
    - pip
  run:
    - python
```
