### ISSUE TITLE
Skip writing sha256_in_prefix if it is the same as the original sha256

### ISSUE THREAD

**Issue by wolfv** [conda/rattler#471]
Rattler currently writes both sha's, even if they are identical:

```yaml
    - _path: site-packages/pip/_internal/commands/wheel.py
      path_type: hardlink
      sha256: 99b14977876651fad51499106caf27db31f245c0f7008f757fb114a3d9772988
      sha256_in_prefix: 99b14977876651fad51499106caf27db31f245c0f7008f757fb114a3d9772988
      size_in_bytes: 7396
```

I think we should write only `sha256`, and if they are not identical, also write the `sha256_in_prefix`. IIRC that is how `conda` handles it.
