### ISSUE TITLE
No solve on osx-64 platfrom when a dependency does not support Python 3.13

### ISSUE THREAD

**Issue by hoxbro** [conda/rattler#913]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

Starting to see failing to solve for the osx-64 platform ([6 hours and cancel](https://github.com/holoviz/datashader/actions/runs/11555538619/job/32173996834)). I think this is because of Python 3.13 + numba (which currently does not support Python 3.13). This is a (reduced) pixi.toml file and using this command: `rm -rf pixi.lock .pixi && pixi install`

``` python
[project]
name = "datashader"
channels = ["conda-forge"]
platforms = ["osx-64"]

[dependencies]
colorcet = "*"
numba = "*"
numpy = "*"
pip = "*"
# This takes 14 seconds to solve on osx-64
# Adding more deps now increase the time significant for osx-64
# requests = "*"  # 21 seconds
# setuptools = "*"  # 33 seconds
# pandas = "*"  # ctrl + c after 2.5 minutes
```

Moving numba to the top or adding a `python <3.13` pin will make it solve instant for osx-64. So, likely, the solver gets in a weird state where it never solves.

**Comment by hoxbro** [comment]
Another example is this, the same solution as above. However, numba is about to be released with Python 3.13 support. So will likely not be reproducible before Python 3.14.

``` toml
[project]
name = "spatialpandas"
channels = ["conda-forge"]
platforms = ["osx-64"]

[dependencies]
dask-core = "*"
fsspec = "*"
numba = "*"
packaging = "*"
pandas = "*"
pip = "*"
pyarrow = ">=10"
```
